security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        
    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
            
            logout:       true
            anonymous:    true